baseurl = "https://hidevops.io/"
languageCode = "en-us"
title = "Hiboot"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "John Deng"
	description = "Official site hidevops.io"
	copyright = "Released under the Apache 2.0 license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/hidevopsio/hiboot"

	version = "0.9.5"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "cyan"
    	accent  = "green"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "hidevopsio"
	email   = "hi.devops.io@gmail.com"


# [[menu.main]]
# 	name   = "Material"
# 	url    = "/"
# 	weight = 0

[[menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10

[[menu.main]]
	name   = "Adding content"
	url    = "adding-content/"
	weight = 20

# [[menu.main]]
# 	name   = "Roadmap"
# 	url    = "roadmap/"
# 	weight = 30

# [[menu.main]]
# 	name   = "License"
# 	url    = "license/"
# 	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
