baseurl = "https://hiboot.hidevops.io/"
# languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Hiboot Documentation"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
sectionPagesMenu = "main"
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

# Code highlighting options
# Hugo uses Chroma but names are the same as the old pygments highlighter

# Highlight shortcode and code fences (```) will be treated similarly
pygmentscodefences = true

# Change highlight style here.
# For a full list see: https://xyproto.github.io/splash/docs/all.html
pygmentsStyle = "tango" # "emacs" # "autumn" # "manni" # "friendly"

# Other Chroma options can be added here (and in the highlight shortcode in the markdown file)
# See list of supported options: https://gohugo.io/content-management/syntax-highlighting/#options
# for example: pygmentsoptions = "linenos=true"

[params]
	# General information
	author = "John Deng"
	description = "Official site hidevops.io"
	copyright = "Released under the Apache 2.0 license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/hidevopsio/hiboot"

	version = "0.9.5"
	logo = "images/logo.png"
	favicon = ""

	permalink = " "

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	# Theme color, available values are: red, pink, purple, deep purple, indigo, blue, light-blue, cyan, teal, green, light-green, lime, yellow, amber, orange, deep-orange, brown, grey and blue-grey
	[params.palette]
    	primary = "cyan"
    	accent  = "deep-purple"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[languages]
  [languages.en]
	languageName = "English"
    title = "Hiboot Documentation"
    weight = 1
	contentDir = "content/en-US"
  [languages.cn]
	languageName = "中文"
    title = "Hiboot 文档"
    weight = 2
	contentDir = "content/zh-CN"



[social]
	twitter = "johndcn"
	github  = "hidevopsio"
	email   = "hi.devops.io@gmail.com"

[[menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 1

[[languages.en.menu.main]]
	name   = "Introduction"
	url    = "/"
	weight = 1

[[languages.en.menu.main]]
	name   = "Getting started"
	url    = "getting-started/"
	weight = 10


[[languages.en.menu.main]]
	name   = "Applications"
	url    = "apps/"
	weight = 20

[[languages.en.menu.main]]
	name   = "Inversion of Control"
	url    = "inversion-of-control/"
	weight = 30

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
[outputs]
	home = [ "HTML", "JSON"]
	page = [ "HTML", "JSON"]